# https://docs.mongodb.com/manual/tutorial/deploy-replica-set-for-testing/
version: "3.0"
services:
  mongo0:
    container_name: mongo0
    image: mongo:4
    restart: on-failure
    command: mongod --replSet rs0 --port 27017 --bind_ip localhost,mongo0
    ports: 
      - 27017:27017
    networks:
      - mongo-net
  rplset-setup:
    container_name: rplset-setup
    image: mongo:4
    command:
      |
        ./scripts/wait-for-it.sh mongo0:27017 -- mongo mongo0:27017 --eval 
        'rs.initiate({
          _id: "rs0",
          members: [
            {
              _id: 0,
              host: "mongo0:27017"
            }
          ]
        })'
    networks:       
      - mongo-net
    volumes: 
      - ./:/scripts
  
networks:
  mongo-net: